// Export ABIs from Foundry artifacts (contracts/out) into the keeper and the
// frontend as typed `as const` modules, so neither hand-copies an ABI.
//   cd contracts && forge build && node script/export-abis.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'out');

const CONTRACTS = {
  CERMIN_SAKU_ABI: 'CerminSaku.sol/CerminSaku.json',
  CERMIN_LENS_ABI: 'CerminLens.sol/CerminLens.json',
  CERMIN_VAULT_V11_ABI: 'CerminVault.sol/CerminVault.json',
  CERMIN_FACTORY_V11_ABI: 'CerminFactory.sol/CerminFactory.json',
  MOCK_PRICE_FEED_ABI: 'MockPriceFeed.sol/MockPriceFeed.json',
};

let body = '// Generated by contracts/script/export-abis.mjs from Foundry artifacts. Do not edit.\n';
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(readFileSync(join(out, file), 'utf8'));
  body += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

const targets = [
  join(here, '..', '..', 'agent', 'src', 'abis', 'generated.ts'),
  join(here, '..', '..', 'frontend', 'src', 'lib', 'abis.generated.ts'),
];
for (const t of targets) {
  writeFileSync(t, body);
  console.log('wrote', t);
}
