// Cermin Saku: wire a finished deployment into the web app, the keeper and the README.
//   node scripts/post-deploy.mjs [deployments/bsc-testnet.json] [--site https://…] [--video https://…] [--local]
// --local (fork rehearsal): writes frontend/.env.local pointing at BSC_TESTNET_RPC and leaves README alone.
// Writes only public addresses to frontend/.env.production (committed, so a Vercel build from
// GitHub picks them up). agent/.env (gitignored) gets the keeper key from KEEPER_PRIVATE_KEY in
// the environment; the key is never printed.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const opt = (name) => {
  const i = args.indexOf(`--${name}`);
  return i > -1 ? args[i + 1] : undefined;
};
const depRel = args.find((a, i) => !a.startsWith('--') && !args[i - 1]?.startsWith('--')) ?? 'deployments/bsc-testnet.json';
const depPath = join(root, 'contracts', depRel);
if (!existsSync(depPath)) {
  console.error(`no deployment at contracts/${depRel}; run scripts/deploy-testnet.sh first`);
  process.exit(1);
}
const dep = JSON.parse(readFileSync(depPath, 'utf8'));
const RPC = process.env.BSC_TESTNET_RPC ?? 'https://bsc-testnet-rpc.publicnode.com';
const ZERO = '0x0000000000000000000000000000000000000000';
const SCAN = dep.chainId === 56 ? 'https://bscscan.com' : 'https://testnet.bscscan.com';

async function vaultOf(owner) {
  if (dep.chainId === 31337 && !process.env.BSC_TESTNET_RPC) return ZERO;
  const data = '0x0709df45' + owner.toLowerCase().replace(/^0x/, '').padStart(64, '0'); // vaultOf(address)
  const res = await fetch(RPC, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'eth_call', params: [{ to: dep.CerminFactory, data }, 'latest'] }),
  });
  const { result } = await res.json();
  return result && result.length >= 66 ? '0x' + result.slice(-40) : ZERO;
}

const demoVault = process.env.DEMO_VAULT ?? (await vaultOf(dep.deployer));
const site = opt('site');
const local = args.includes('--local');
const video = opt('video');

// 1. Web app: public addresses only.
const webEnv = [
  `# Generated by scripts/post-deploy.mjs from contracts/${depRel}. Public addresses only, no secrets.`,
  `NEXT_PUBLIC_CHAIN_ID=${dep.chainId}`,
  `NEXT_PUBLIC_CERMIN_FACTORY_ADDRESS=${dep.CerminFactory}`,
  `NEXT_PUBLIC_MUSD_ADDRESS=${dep.MUSD}`,
  `NEXT_PUBLIC_SAVINGS_VAULT_ADDRESS=${dep.SavingsVault}`,
  `NEXT_PUBLIC_PRICE_FEED_ADDRESS=${dep.PriceFeed}`,
  `NEXT_PUBLIC_SAKU_ADDRESS=${dep.CerminSaku}`,
  `NEXT_PUBLIC_LENS_ADDRESS=${dep.CerminLens}`,
  `NEXT_PUBLIC_DEMO_VAULT=${demoVault}`,
  `NEXT_PUBLIC_DEPLOY_BLOCK=${dep.deployBlock}`,
  ...(site ? [`NEXT_PUBLIC_SITE_URL=${site.replace(/\/$/, '')}`] : []),
  ...(local ? [`NEXT_PUBLIC_BSC_RPC_URL=${RPC}`] : []),
  '',
].join('\n');
const webFile = local ? '.env.local' : '.env.production';
writeFileSync(join(root, 'frontend', webFile), webEnv);
console.log(`frontend/${webFile} written (demo vault ${demoVault})`);

// 2. Keeper: agent/.env (gitignored). Key from env only.
if (process.env.KEEPER_PRIVATE_KEY) {
  const agentEnv = [
    '# Generated by scripts/post-deploy.mjs. Gitignored. Contains the testnet keeper key.',
    `CHAIN_ID=${dep.chainId}`,
    `BSC_RPC_URL=${RPC}`,
    `PRIVATE_KEY=${process.env.KEEPER_PRIVATE_KEY}`,
    `CERMIN_FACTORY_ADDRESS=${dep.CerminFactory}`,
    `PRICE_FEED_ADDRESS=${dep.PriceFeed}`,
    `SAKU_ADDRESS=${dep.CerminSaku}`,
    `MUSD_ADDRESS=${dep.MUSD}`,
    `SAVINGS_VAULT_ADDRESS=${dep.SavingsVault}`,
    'SAKU_HOLD_COOLDOWN_MS=300000',
    'POLL_INTERVAL_MS=30000',
    'YIELD_ENABLED=false',
    'DB_PATH=./data/cermin.db',
    'LOG_LEVEL=info',
    'HEALTH_PORT=8080',
    '',
  ].join('\n');
  writeFileSync(join(root, 'agent', '.env'), agentEnv);
  console.log('agent/.env written (keeper key from env, not shown)');
}

if (local) {
  console.log('local rehearsal: README untouched. Web: cd frontend && npm run dev');
  process.exit(0);
}

// 3. README: contracts table and proof links.
const rows = [
  ['CerminSaku', 'new · schedules, `release`, holds'],
  ['CerminLens', 'new · what-if price views'],
  ['CerminFactory', 'Kiel · clones vaults'],
  ['CerminVaultImpl', 'Kiel + Saku gates (v1.1 implementation)'],
  ['PriceFeed', 'simulated BNB/USD (MockPriceFeed, seeded from Chainlink)'],
  ['MUSD', 'mock stablecoin'],
  ['BorrowerOperations', 'mock CDP'],
  ['TroveManager', 'mock CDP'],
  ['SavingsVault', 'mock savings (sMUSD)'],
].filter(([k]) => dep[k]);
const link = (a) => `[\`${a}\`](${SCAN}/address/${a})`;
const contracts = [
  `**BSC testnet (chain ${dep.chainId})**, deployed from \`${dep.deployer}\` at block ${dep.deployBlock}. Source verified on [Sourcify](https://repo.sourcify.dev/${dep.chainId}/${dep.CerminSaku}).`,
  '',
  '| Contract | Address | Role |',
  '|---|---|---|',
  ...rows.map(([k, role]) => `| ${k} | ${link(dep[k])} | ${role} |`),
  ...(demoVault !== ZERO ? [`| Demo vault | ${link(demoVault)} | the vault shown on \`/bukti\` |`] : []),
].join('\n');
const proof = [
  site ? `Live app: [${site.replace(/^https?:\/\//, '')}](${site})` : 'Live app: *pending*',
  video ? `Demo video: [YouTube](${video})` : 'Demo video: *pending*',
  site ? `On-chain proof page: [/bukti](${site.replace(/\/$/, '')}/bukti)` : 'On-chain proof page: *pending*',
  `[Contracts on BscScan](#contracts)`,
].join(' · ');

const readmePath = join(root, 'README.md');
let readme = readFileSync(readmePath, 'utf8');
const swap = (tag, body) => {
  const re = new RegExp(`(<!-- ${tag}:START -->)[\\s\\S]*?(<!-- ${tag}:END -->)`);
  if (!re.test(readme)) throw new Error(`README marker ${tag} missing`);
  readme = readme.replace(re, `$1\n${body}\n$2`);
};
swap('CONTRACTS', contracts);
swap('PROOF-LINKS', proof);
readme = readme.replace(
  /\| BSC testnet deployment from our own wallet \| [^\n]*/,
  `| BSC testnet deployment from our own wallet | ${dep.CerminSaku ? `CerminSaku ${link(dep.CerminSaku)} and 8 more, source on Sourcify` : 'see Contracts'} | [Contracts](#contracts) |`,
);
writeFileSync(readmePath, readme);
console.log('README.md contracts table + proof links updated');

console.log(`
Next:
  1. git add frontend/.env.production README.md && git commit -m "chore: wire BSC testnet deployment"
  2. Keeper: cd agent && npm run keeper   (reads agent/.env; keep it running during the demo recording)
  3. Vercel: root directory = frontend; no env vars needed (they come from .env.production)
  4. After Vercel/YouTube exist: node scripts/post-deploy.mjs --site <url> --video <url>`);
